import type { StudentWithDetails } from "../types/database"

// Mock data for Vietnamese student management system
export const mockStudents: StudentWithDetails[] = [
  {
    id: "1",
    userId: "user1",
    studentCode: "CST-FB09C1C8BB16",
    dateOfBirth: new Date("2005-01-15"),
    gender: "Nam",
    address: "Hà Nội",
    grade: "12",
    className: "12A1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    user: {
      id: "user1",
      email: "amslink@gmail.com",
      password: "",
      fullName: "Nguyễn Amslink",
      phone: '',
      role: "student",
      username: "amslink@centerup",
      isActive: true,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalCourses: 2,
    totalClasses: 1,
    averageGrade: 0,
    status: "Chờ xếp lớp",
    statusCount: 1,
  },
  {
    id: "2",
    userId: "user2",
    studentCode: "CST-8D333A5D1683",
    dateOfBirth: new Date("2005-03-20"),
    gender: "Nam",
    address: "TP.HCM",
    grade: "11",
    className: "11B2",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
    user: {
      id: "user2",
      email: "hvdara2@gmail.com",
      password: "",
      fullName: "HVDara2",
      phone: "",
      role: "student",
      username: "hvdara2@centerup",
      isActive: true,
      createdAt: new Date("2024-01-02"),
      updatedAt: new Date("2024-01-02"),
    },
    totalCourses: 2,
    totalClasses: 1,
    averageGrade: 6.5,
    status: "Chờ xếp lớp",
    statusCount: 1,
  },
  {
    id: "3",
    userId: "user3",
    studentCode: "CST-64EA6D9B5409",
    dateOfBirth: new Date("2006-05-08"),
    gender: "Nữ",
    address: "Đà Nẵng",
    grade: "10",
    className: "10C1",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
    user: {
      id: "user3",
      email: "tranphuonglinh@gmail.com",
      password: "",
      fullName: "Trần Phương Linh",
      phone: "0904786266",
      role: "student",
      username: "tranphuonglinh@centerup",
      isActive: true,
      createdAt: new Date("2024-01-03"),
      updatedAt: new Date("2024-01-03"),
    },
    totalCourses: 2,
    totalClasses: 0,
    averageGrade: 0,
    status: "Chờ xếp lớp",
    statusCount: 2,
  },
  {
    id: "4",
    userId: "user4",
    studentCode: "CST-CE6FA8F73F7C",
    dateOfBirth: new Date("2005-12-10"),
    gender: "Nam",
    address: "Hải Phòng",
    grade: "11",
    className: "11A3",
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04"),
    user: {
      id: "user4",
      email: "",
      password: "",
      fullName: "Thành",
      phone: "0987654322",
      role: "student",
      username: "thanh25@centerup",
      isActive: true,
      createdAt: new Date("2024-01-04"),
      updatedAt: new Date("2024-01-04"),
    },
    totalCourses: 2,
    totalClasses: 0,
    averageGrade: 0,
    status: "Chờ xếp lớp",
    statusCount: 2,
  },
  {
    id: "5",
    userId: "user5",
    studentCode: "CST-75017FF5A611",
    dateOfBirth: new Date("2004-08-25"),
    gender: "Nam",
    address: "Cần Thơ",
    grade: "12",
    className: "12B1",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    user: {
      id: "user5",
      email: "",
      password: "",
      fullName: "Nguyễn Văn Ngân",
      phone: "0321123321",
      role: "student",
      username: "ngan@centerup",
      isActive: true,
      createdAt: new Date("2024-01-05"),
      updatedAt: new Date("2024-01-05"),
    },
    totalCourses: 4,
    totalClasses: 3,
    averageGrade: 10,
    status: "Đang học",
    statusCount: 2,
  },
  {
    id: "6",
    userId: "user6",
    studentCode: "CST-1DF158FAC62B",
    dateOfBirth: new Date("2005-11-30"),
    gender: "Nam",
    address: "Huế",
    grade: "11",
    className: "11C2",
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-06"),
    user: {
      id: "user6",
      email: "",
      password: "",
      fullName: "Mộng Tuyền - MN Trâm Chim",
      phone: "0702314252",
      role: "student",
      username: "mongtuyentranchim@centerup",
      isActive: true,
      createdAt: new Date("2024-01-06"),
      updatedAt: new Date("2024-01-06"),
    },
    totalCourses: 4,
    totalClasses: 2,
    averageGrade: 0,
    status: "Đang học",
    statusCount: 2,
  },
  {
    id: "7",
    userId: "user7",
    studentCode: "",
    dateOfBirth: new Date("2006-02-14"),
    gender: "Nam",
    address: "Vũng Tàu",
    grade: "10",
    className: "10A2",
    createdAt: new Date("2024-01-07"),
    updatedAt: new Date("2024-01-07"),
    user: {
      id: "user7",
      email: "abc@gmail.com",
      password: "",
      fullName: "Nguyen van A",
      phone: "",
      role: "student",
      username: "abc@centerup",
      isActive: true,
      createdAt: new Date("2024-01-07"),
      updatedAt: new Date("2024-01-07"),
    },
    totalCourses: 1,
    totalClasses: 0,
    averageGrade: 0,
    status: "Chờ xếp lớp",
    statusCount: 1,
  },
]

export const statusCounts = {
  all: 119,
  pending: 44, // Chờ xếp lớp
  upcoming: 0, // Sắp học
  studying: 27, // Đang học
  reserved: 0, // Bảo lưu
  stopped: 42, // Dừng học
  graduated: 2, // Tốt nghiệp
}
