import { ClassAttendanceHistory } from "../components/attendance/class-attendance-history"

// Mock data for demonstration
const mockStudents = [
	{
		id: "1",
		userId: "u1",
		studentCode: "ST001",
		grade: "10A",
		user: {
			id: "u1",
			fullName: "Nguyễn Văn An",
			avatar: "/diverse-students-studying.png",
			email: "an.nguyen@example.com",
		},
	},
	{
		id: "2",
		userId: "u2",
		studentCode: "ST002",
		grade: "10A",
		user: {
			id: "u2",
			fullName: "Trần Thị Bình",
			avatar: "/diverse-students-studying.png",
			email: "binh.tran@example.com",
		},
	},
	{
		id: "3",
		userId: "u3",
		studentCode: "ST003",
		grade: "10A",
		user: {
			id: "u3",
			fullName: "Lê Văn Cường",
			avatar: "/diverse-students-studying.png",
			email: "cuong.le@example.com",
		},
	},
	{
		id: "4",
		userId: "u4",
		studentCode: "ST004",
		grade: "10A",
		user: {
			id: "u4",
			fullName: "Phạm Thị Dung",
			avatar: "/diverse-students-studying.png",
			email: "dung.pham@example.com",
		},
	},
	{
		id: "5",
		userId: "u5",
		studentCode: "ST005",
		grade: "10A",
		user: {
			id: "u5",
			fullName: "Hoàng Văn Em",
			avatar: "/diverse-students-studying.png",
			email: "em.hoang@example.com",
		},
	},
]

const mockAttendanceRecords = [
	{
		session: {
			id: "s1",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-15"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 1,
				sessionId: "s1",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-15T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 2,
				sessionId: "s1",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-15T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 3,
				sessionId: "s1",
				studentId: "3",
				status: "late",
				note: "Đến muộn 10 phút",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-15T08:10:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 4,
				sessionId: "s1",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-15T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 5,
				sessionId: "s1",
				studentId: "5",
				status: "absent",
				note: "Không có lý do",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-15T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s2",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-17"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 6,
				sessionId: "s2",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-17T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 7,
				sessionId: "s2",
				studentId: "2",
				status: "excused",
				note: "Nghỉ ốm có giấy phép",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-17T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 8,
				sessionId: "s2",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-17T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 9,
				sessionId: "s2",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-17T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 10,
				sessionId: "s2",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-17T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s3",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-19"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Kiểm tra giữa kỳ",
		},
		attendances: [
			{
				id: 11,
				sessionId: "s3",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 12,
				sessionId: "s3",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 13,
				sessionId: "s3",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 14,
				sessionId: "s3",
				studentId: "4",
				status: "late",
				note: "Đến muộn 5 phút",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-19T08:05:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 15,
				sessionId: "s3",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s4",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-22"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 16,
				sessionId: "s4",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-22T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 17,
				sessionId: "s4",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-22T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 18,
				sessionId: "s4",
				studentId: "3",
				status: "absent",
				note: "Không có lý do",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-22T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 19,
				sessionId: "s4",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-22T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 20,
				sessionId: "s4",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-22T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s5",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-24"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 21,
				sessionId: "s5",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-24T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 22,
				sessionId: "s5",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-24T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 23,
				sessionId: "s5",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-24T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 24,
				sessionId: "s5",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-24T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 25,
				sessionId: "s5",
				studentId: "5",
				status: "excused",
				note: "Nghỉ có phép gia đình",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-24T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s6",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-26"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 26,
				sessionId: "s6",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 27,
				sessionId: "s6",
				studentId: "2",
				status: "late",
				note: "Trễ xe buýt",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-26T08:15:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 28,
				sessionId: "s6",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 29,
				sessionId: "s6",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 30,
				sessionId: "s6",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s7",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-29"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Bài tập nhóm",
		},
		attendances: [
			{
				id: 31,
				sessionId: "s7",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-29T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 32,
				sessionId: "s7",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-29T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 33,
				sessionId: "s7",
				studentId: "3",
				status: "absent",
				note: "Ốm không đến được",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-29T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 34,
				sessionId: "s7",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-29T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 35,
				sessionId: "s7",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-29T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s8",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-01-31"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 36,
				sessionId: "s8",
				studentId: "1",
				status: "excused",
				note: "Có việc gia đình",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-31T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 37,
				sessionId: "s8",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-31T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 38,
				sessionId: "s8",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-31T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 39,
				sessionId: "s8",
				studentId: "4",
				status: "late",
				note: "Tắc đường",
				recordedBy: "t1",
				recordedAt: new Date("2024-01-31T08:20:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 40,
				sessionId: "s8",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-01-31T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s9",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-02"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Thảo luận chương mới",
		},
		attendances: [
			{
				id: 41,
				sessionId: "s9",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 42,
				sessionId: "s9",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 43,
				sessionId: "s9",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 44,
				sessionId: "s9",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 45,
				sessionId: "s9",
				studentId: "5",
				status: "absent",
				note: "Không báo trước",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s10",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-05"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 46,
				sessionId: "s10",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 47,
				sessionId: "s10",
				studentId: "2",
				status: "late",
				note: "Quên báo thức",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-05T08:12:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 48,
				sessionId: "s10",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 49,
				sessionId: "s10",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 50,
				sessionId: "s10",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s11",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-07"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Kiểm tra 15 phút",
		},
		attendances: [
			{
				id: 51,
				sessionId: "s11",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 52,
				sessionId: "s11",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 53,
				sessionId: "s11",
				studentId: "3",
				status: "excused",
				note: "Đi khám bệnh",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 54,
				sessionId: "s11",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 55,
				sessionId: "s11",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s12",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-09"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 56,
				sessionId: "s12",
				studentId: "1",
				status: "late",
				note: "Xe hỏng trên đường",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-09T08:25:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 57,
				sessionId: "s12",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 58,
				sessionId: "s12",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 59,
				sessionId: "s12",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 60,
				sessionId: "s12",
				studentId: "5",
				status: "absent",
				note: "Nghỉ không phép",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s13",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-12"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Presentation nhóm",
		},
		attendances: [
			{
				id: 61,
				sessionId: "s13",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 62,
				sessionId: "s13",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 63,
				sessionId: "s13",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 64,
				sessionId: "s13",
				studentId: "4",
				status: "excused",
				note: "Tham gia cuộc thi",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 65,
				sessionId: "s13",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s14",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-14"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 66,
				sessionId: "s14",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-14T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 67,
				sessionId: "s14",
				studentId: "2",
				status: "absent",
				note: "Ốm nặng",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-14T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 68,
				sessionId: "s14",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-14T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 69,
				sessionId: "s14",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-14T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 70,
				sessionId: "s14",
				studentId: "5",
				status: "late",
				note: "Mưa to, tắc đường",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-14T08:18:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s15",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-16"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Ôn tập cuối chương",
		},
		attendances: [
			{
				id: 71,
				sessionId: "s15",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-16T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 72,
				sessionId: "s15",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-16T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 73,
				sessionId: "s15",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-16T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 74,
				sessionId: "s15",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-16T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 75,
				sessionId: "s15",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-16T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s16",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-19"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Kiểm tra cuối chương",
		},
		attendances: [
			{
				id: 76,
				sessionId: "s16",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 77,
				sessionId: "s16",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 78,
				sessionId: "s16",
				studentId: "3",
				status: "late",
				note: "Đi muộn vì ùn tắc",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-19T08:08:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 79,
				sessionId: "s16",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 80,
				sessionId: "s16",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-19T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s17",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-21"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 81,
				sessionId: "s17",
				studentId: "1",
				status: "excused",
				note: "Đi khám sức khỏe định kỳ",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-21T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 82,
				sessionId: "s17",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-21T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 83,
				sessionId: "s17",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-21T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 84,
				sessionId: "s17",
				studentId: "4",
				status: "absent",
				note: "Ốm đột xuất",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-21T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 85,
				sessionId: "s17",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-21T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s18",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-23"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Bắt đầu chương mới",
		},
		attendances: [
			{
				id: 86,
				sessionId: "s18",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-23T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 87,
				sessionId: "s18",
				studentId: "2",
				status: "late",
				note: "Xe máy bị hỏng",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-23T08:22:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 88,
				sessionId: "s18",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-23T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 89,
				sessionId: "s18",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-23T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 90,
				sessionId: "s18",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-23T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s19",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-26"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 91,
				sessionId: "s19",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 92,
				sessionId: "s19",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 93,
				sessionId: "s19",
				studentId: "3",
				status: "absent",
				note: "Nghỉ không báo trước",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 94,
				sessionId: "s19",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 95,
				sessionId: "s19",
				studentId: "5",
				status: "excused",
				note: "Tham dự lễ tang gia đình",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-26T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s20",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-02-28"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Thực hành bài tập",
		},
		attendances: [
			{
				id: 96,
				sessionId: "s20",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-28T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 97,
				sessionId: "s20",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-28T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 98,
				sessionId: "s20",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-28T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 99,
				sessionId: "s20",
				studentId: "4",
				status: "late",
				note: "Làm thủ tục hành chính",
				recordedBy: "t1",
				recordedAt: new Date("2024-02-28T08:13:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 100,
				sessionId: "s20",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-02-28T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s21",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-03-02"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 101,
				sessionId: "s21",
				studentId: "1",
				status: "late",
				note: "Bị kẹt thang máy",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-02T08:17:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 102,
				sessionId: "s21",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 103,
				sessionId: "s21",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 104,
				sessionId: "s21",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 105,
				sessionId: "s21",
				studentId: "5",
				status: "absent",
				note: "Sốt cao không đến được",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-02T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s22",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-03-05"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Seminar học sinh",
		},
		attendances: [
			{
				id: 106,
				sessionId: "s22",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 107,
				sessionId: "s22",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 108,
				sessionId: "s22",
				studentId: "3",
				status: "excused",
				note: "Tham gia hội thảo khoa học",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 109,
				sessionId: "s22",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 110,
				sessionId: "s22",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-05T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s23",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-03-07"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: null,
		},
		attendances: [
			{
				id: 111,
				sessionId: "s23",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 112,
				sessionId: "s23",
				studentId: "2",
				status: "absent",
				note: "Nghỉ vì việc cá nhân",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 113,
				sessionId: "s23",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 114,
				sessionId: "s23",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-07T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 115,
				sessionId: "s23",
				studentId: "5",
				status: "late",
				note: "Đi khám răng",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-07T08:30:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s24",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-03-09"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Kiểm tra giữa học kỳ 2",
		},
		attendances: [
			{
				id: 116,
				sessionId: "s24",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 117,
				sessionId: "s24",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 118,
				sessionId: "s24",
				studentId: "3",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 119,
				sessionId: "s24",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 120,
				sessionId: "s24",
				studentId: "5",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-09T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
	{
		session: {
			id: "s25",
			classId: "c1",
			academicYear: "2024-2025",
			sessionDate: new Date("2024-03-12"),
			startTime: "08:00",
			endTime: "09:30",
			status: "completed",
			notes: "Chữa bài kiểm tra",
		},
		attendances: [
			{
				id: 121,
				sessionId: "s25",
				studentId: "1",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 122,
				sessionId: "s25",
				studentId: "2",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 123,
				sessionId: "s25",
				studentId: "3",
				status: "late",
				note: "Phụ giúp gia đình",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-12T08:14:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 124,
				sessionId: "s25",
				studentId: "4",
				status: "present",
				note: null,
				recordedBy: "t1",
				recordedAt: new Date("2024-03-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
			{
				id: 125,
				sessionId: "s25",
				studentId: "5",
				status: "excused",
				note: "Đi thi Olympic Toán",
				recordedBy: "t1",
				recordedAt: new Date("2024-03-12T08:00:00"),
				recordedByUser: { id: "t1", fullName: "Giáo viên A" },
			},
		],
	},
]

export default function ClassAttendancePage({
	teacherClassAssignmentId,
}: {
	teacherClassAssignmentId: any
}) {
	return (
		<div className="container mx-auto py-8 px-4">
			<ClassAttendanceHistory
				classId={teacherClassAssignmentId}
				className="Toán 10A - Học kỳ 1"
				students={mockStudents}
				attendanceRecords={mockAttendanceRecords}
			/>
		</div>
	)
}
